4. Verificación de Código Estático
lvzh90/workshop-api-testing-js pull request #5
Opened 2018-02-25 02:18 UTC by lvzh90

4. Verificación de Código Estático

2018-02-25 02:29 UTC, aperdomob requested changes
Revisa porque está fallando

2018-02-25 02:29 UTC, aperdomob commented on .eslintrc.yml
> +
Elimina los espacios

2018-02-26 12:29 UTC, lvzh90 commented on .eslintrc.yml
> +
Hecho

2018-02-26 14:14 UTC, aperdomob approved these changes

2018-02-26 14:19 UTC, merged